### ISSUE TITLE
Plans for this repo?

### ISSUE THREAD

**Issue by good-praxis** [jglrxavpok/Vulkan-Tutorial-Implementation#3]
Hey, opening an issue since you didn't have a contact email listed. Did you initially plan on replicating the entire vulkan tutorial with this repo? Is this still an active plan?

You come up with a few very good solutions for translating the cpp code to kotlin (like using the not operator for replicating pointer functionality). If you don't intend to continue this project I'd love to start building a replication on my own, using some of your methods to simplicity & crediting you, of course.

Unless you're still following this up on your own, of course.

**Comment by jglrxavpok** [comment]
The plan was to replicate the entire tutorial, so I could learn the in and outs of Vulkan. I got busy with other projects and life so I haven't been able to work on this repo for a while.

I will probably continue this repo in the future, but that's not before a few months time: don't hesitate to do your own project. Try to comment the code a bit more than I did, I really failed on this point in this repo...

Keep me up to date, as I am curious to see how you translate the logic into Kotlin!

PD: I've listed my contact email.
